### ISSUE TITLE
Dienst2 Google Directory API TODO's

### ISSUE THREAD

**Issue by JoepdeJong** [WISVCH/dienst2#324]
- [x] Create a `root` user in Google Workspace and use it in `GOOGLE_SERVICE_ACCOUNT_DELEGATED_USER`
- [ ] Cache the indirect groups
- [ ] Remove hardcoded indirect groups

**Comment by praseodym** [comment]
How do we want to keep track of Google Workspace usernames and email aliases?

**Comment by JoepdeJong** [comment]
> How do we want to keep track of Google Workspace usernames and email aliases?
That is already in Dienst2! Validation is also implemented: https://github.com/WISVCH/dienst2/blob/bdfd9b56eb16039869c7f2fd9ab636e674a718ba/ldb/validators.py#LL18C52-L18C52
<img width="546" alt="Screenshot 2023-05-24 at 14 44 29" src="https://github.com/WISVCH/dienst2/assets/7187634/96ce9913-bca0-4e2b-8e75-f61eee7b8704">

**Comment by JoepdeJong** [comment]
(It is not yet synced with Google)

**Comment by JoepdeJong** [comment]
since we now have connect 2, we do not need this at the moment.

for dienst2, direct groups are sufficient. would be nice to have a future that allows assigning groups to members in dienst2. but this has no priority at the moment.
